### ISSUE TITLE
less plot armor

### ISSUE THREAD

**Issue by Gurkenglas** [AlexBuz/mindsweeper#4]
Some of the more skill-testing scenarios in minesweeper were when one has to pick the least bad move. Should there be a toggle that turns the game from "guessing is *never* necessary" into "Your score is your survival probability, which starts at 1. Every time you guess, you turn out to be correct, but your score is multiplied by the chance that your guess was correct."? You could call the negative logarithm of the score "Years of luck spent" :)

**Comment by AlexBuz** [comment]
Thank you for the feedback! This is an interesting idea, but as of now it's outside the scope of what I'd like to accomplish with mindsweeper. Fundamentally, my goal was always to eliminate the need to think about probabilities at all, as I think there's a certain niceness to the simplicity of that. Also, a mode like this might be difficult to balance, since some games would still not require guessing and you could win with perfect score of 0. That is, unless I were to somehow calculate the minimum amount guessing required to win and base the score off of how much *extra* guessing the player does. Still, though, I'm not sure I'm too keen on incorporating probabilities into the game mechanics currently.

There is another part of your suggestion that I had more seriously considered implementing at one point though:
> Every time you guess, you turn out to be correct

This would effectively be the opposite of the existing guess punishment feature, since with such a feature enabled, if you reveal a tile that may or may not be a mine, it will in fact **not** be a mine, guaranteed. However, with such a feature, I fear one could always reveal unconstrained tiles and clear most of the board without much thought at all, so I'm not confident that this would make for a very enjoyable game mode. As such, I'm going to close this as not planned.
